### ISSUE TITLE
$(fetch) sends literal JSON, but in docs it sends the value of a property

### ISSUE THREAD

**Issue by SethFalco** [botisimo/botisimo-documentation#3]
![image](https://user-images.githubusercontent.com/22801583/153725119-9fe75e8e-6b8e-4a7a-8ffa-a0064facc106.png)

In the $(fetch) section of the docs, you use an API that returns JSON, but the documented output only includes the value of the `quote` property. 🤔 

I've just tried to do this similarly myself with another API that returns output like:
```json
{
  "output": "…"
}
```

But the message sent is the literal JSON, now just the value of the first property like what the docs suggest.

Could you tell me if I'm doing something wrong, or if the docs are just outdated?

**Comment by SethFalco** [comment]
Ahh… didn't occur to me until after.

It could also be that the `?format=text` query parameter you're using is no longer supported? So the example request you're using is returning a JSON object, not text. I see nothing about that in the repo for the API you're referencing either.

**Comment by otothea** [comment]
If api returns json you should be able to pass a second argument with a string path to the value you want.

In this case, it would be:
`$(fetch https://api.kanye.rest/ output)`

But it could be more complex:
`$(fetch https://some-api.com/endpoint path.to.my.value)`

Please let me know if that works for you.

**Comment by SethFalco** [comment]
> If api returns json you should be able to pass a second argument with a string path to the value you want.

Just checking, are you describing what the platform does now, or suggesting a feature request?

**Comment by otothea** [comment]
I'm suggesting what it does now

**Comment by SethFalco** [comment]
Ahhh yeah, you're correct.
If someone else (or you) doesn't do it already, I'll open a PR later this evening to update the docs with the 2nd argument and include that in the example.

Thanks for the help!

**Comment by otothea** [comment]
Awesome! Will happily review any PRs you send our way. Thanks!

**Comment by otothea** [comment]
Took a quick peak at that kanye api and it seems like they did in fact remove the support for different response types in this commit

https://github.com/ajzbc/kanye.rest/commit/2c7e65e1cba8671a4b7cae3bcbac93611714c794

**Comment by SethFalco** [comment]
Could I just ask, does the 2nd argument work if it's JSON only?
Or does it also work for XML for example?

Just want to note that it's for JSON responses only if that's the case.
